### ISSUE TITLE
翻译这么多了啊

### ISSUE THREAD

**Issue by TobinXu** [LiUzHiAn/simpleDB-gitbook#1]
翻译这么多了啊，老多了哈哈哈哈

**Comment by LiUzHiAn** [comment]
其实也还没算完，个人觉得研究到这就差不多了。😁

**Comment by TobinXu** [comment]
> 其实也还没算完，个人觉得研究到这就差不多了。😁

可以的，可以去相关论坛分享，star会多些吧
